### ISSUE TITLE
Crashed Project

### ISSUE THREAD

**Issue by kWhittington** [ascendro/redmine_issue_reminder#24]
I'm running Redmine 1.4 w/PostgreSQL on a Linux server.
After installing the plugin, I enabled it on a project and now am not able to access it.

I am getting a routes error:
Processing ProjectsController#show (for {user-ip-address} at 2012-11-14 16:24:45) [GET]
  Parameters: {"jump"=>"settings", "action"=>"show", "id"=>{project-name}, "controller"=>"projects"}
Redirected to {project-settings-url}
Completed in 7ms (DB: 2) | 302 Found [project-url?jump=settings]

Processing ProjectsController#settings (for {user-ip-address} at 2012-11-14 16:24:45) [GET]
  Parameters: {"action"=>"settings", "id"=>{project-name}, "controller"=>"projects"}
Rendering template within layouts/base
Rendering projects/settings

ActionView::TemplateError (No route matches {:project_id=>#<Project id: 3, name: {project-name}, description: {project-description}, homepage: "", is_public: false, parent_id: nil, created_on: "2012-04-19 21:56:24", updated_on: "2012-05-16 05:58:15", identifier: {project-identifier}, status: 1, lft: 23, rgt: 30>, :action=>"index", :controller=>"reminders"}) on line #57 of app/views/layouts/base.html.erb:
54:
55:     <% if display_main_menu?(@project) %>
56:     <div id="main-menu">
57:         <%= render_main_menu(@project) %>
58:     </div>
59:     <% end %>
60: </div>

```
lib/redmine/menu_manager.rb:150:in `render_single_menu_node'
lib/redmine/menu_manager.rb:102:in `render_menu_node'
lib/redmine/menu_manager.rb:91:in `render_menu'
lib/redmine/menu_manager.rb:168:in `menu_items_for'
lib/redmine/menu_manager.rb:165:in `each'
lib/redmine/menu_manager.rb:165:in `menu_items_for'
lib/redmine/menu_manager.rb:90:in `render_menu'
lib/redmine/menu_manager.rb:80:in `render_main_menu'
app/views/layouts/base.html.erb:57
passenger (3.0.9) lib/phusion_passenger/rack/request_handler.rb:96:in `process_request'
passenger (3.0.9) lib/phusion_passenger/abstract_request_handler.rb:513:in `accept_and_process_next_request'
passenger (3.0.9) lib/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
passenger (3.0.9) lib/phusion_passenger/classic_rails/application_spawner.rb:321:in `start_request_handler'
passenger (3.0.9) lib/phusion_passenger/classic_rails/application_spawner.rb:275:in `send'
passenger (3.0.9) lib/phusion_passenger/classic_rails/application_spawner.rb:275:in `handle_spawn_application'
passenger (3.0.9) lib/phusion_passenger/utils.rb:479:in `safe_fork'
passenger (3.0.9) lib/phusion_passenger/classic_rails/application_spawner.rb:270:in `handle_spawn_application'
passenger (3.0.9) lib/phusion_passenger/abstract_server.rb:357:in `__send__'
passenger (3.0.9) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
passenger (3.0.9) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
passenger (3.0.9) lib/phusion_passenger/abstract_server.rb:180:in `start'
passenger (3.0.9) lib/phusion_passenger/classic_rails/application_spawner.rb:149:in `start'
passenger (3.0.9) lib/phusion_passenger/spawn_manager.rb:219:in `spawn_rails_application'
passenger (3.0.9) lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
passenger (3.0.9) lib/phusion_passenger/spawn_manager.rb:214:in `spawn_rails_application'
passenger (3.0.9) lib/phusion_passenger/abstract_server_collection.rb:82:in `synchronize'
passenger (3.0.9) lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
passenger (3.0.9) lib/phusion_passenger/spawn_manager.rb:213:in `spawn_rails_application'
passenger (3.0.9) lib/phusion_passenger/spawn_manager.rb:132:in `spawn_application'
passenger (3.0.9) lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
passenger (3.0.9) lib/phusion_passenger/abstract_server.rb:357:in `__send__'
passenger (3.0.9) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
passenger (3.0.9) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
passenger (3.0.9) helper-scripts/passenger-spawn-server:99
```

Rendering {redmine-url}500.html (500 Internal Server Error)

**Comment by MichaelKling** [comment]
i just merged an update for 1.4 compatibility (see #26) - on the other side it looks like thats not the issue here.
