### ISSUE TITLE
Install on Redmine 3.1.3

### ISSUE THREAD

**Issue by lordotter** [ascendro/redmine_issue_reminder#35]
I followed the Installation procedure and during the command

``` bash
RAILS_ENV=production bundle exec rake db:migrate --trace
```

in the Folder of this Plugin, I got this error

``` bash
RAILS_ENV=production bundle exec rake db:migrate --trace
(in /opt/redmine/redmine-3.1)
rake aborted!
NameError: uninitialized constant ActionDispatch::XmlParamsParser
/opt/redmine/redmine-3.1/config/application.rb:52:in `<class:Application>'
/opt/redmine/redmine-3.1/config/application.rb:8:in `<module:RedmineApp>'
/opt/redmine/redmine-3.1/config/application.rb:7:in `<top (required)>'
/opt/redmine/redmine-3.1/Rakefile:5:in `require'
/opt/redmine/redmine-3.1/Rakefile:5:in `<top (required)>'
/usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load'
/usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load_rakefile'
/usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:689:in `raw_load_rakefile'
/usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:94:in `block in load_rakefile'
/usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:93:in `load_rakefile'
/usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:77:in `block in run'
/usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/usr/local/rvm/rubies/ruby-2.2.3/bin/rake:33:in `<main>'
```

And no Table was created.

I use

```
Environment:
  Redmine version                3.1.3.stable
  Ruby version                   2.2.3-p173 (2015-08-18) [x86_64-linux]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            1.8.3.1
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.3.12
  redmine_checklists             3.1.3
  redmine_planning               1.0.0
```

**Comment by necroman135** [comment]
I couldnt install 3.1.3 also help please
